// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchExtract(arg1, arg2) {
  return window['go']['app']['App']['BatchExtract'](arg1, arg2);
}

export function Compress(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Compress'](arg1, arg2, arg3, arg4);
}

export function DeletePasswordRecord(arg1) {
  return window['go']['app']['App']['DeletePasswordRecord'](arg1);
}

export function Extract(arg1, arg2) {
  return window['go']['app']['App']['Extract'](arg1, arg2);
}

export function ExtractWithPassword(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExtractWithPassword'](arg1, arg2, arg3);
}

export function ExtractWithRetry(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExtractWithRetry'](arg1, arg2, arg3);
}

export function ExtractWithStrategy(arg1, arg2) {
  return window['go']['app']['App']['ExtractWithStrategy'](arg1, arg2);
}

export function GetAppConfig(arg1) {
  return window['go']['app']['App']['GetAppConfig'](arg1);
}

export function GetExtractStrategies() {
  return window['go']['app']['App']['GetExtractStrategies']();
}

export function GetExtractStrategy(arg1) {
  return window['go']['app']['App']['GetExtractStrategy'](arg1);
}

export function GetHistory(arg1) {
  return window['go']['app']['App']['GetHistory'](arg1);
}

export function GetPasswordCandidates(arg1) {
  return window['go']['app']['App']['GetPasswordCandidates'](arg1);
}

export function GetPasswordRecords() {
  return window['go']['app']['App']['GetPasswordRecords']();
}

export function GetPasswordStats() {
  return window['go']['app']['App']['GetPasswordStats']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function OpenDirectory(arg1) {
  return window['go']['app']['App']['OpenDirectory'](arg1);
}

export function PreviewArchive(arg1) {
  return window['go']['app']['App']['PreviewArchive'](arg1);
}

export function SaveExtractStrategy(arg1) {
  return window['go']['app']['App']['SaveExtractStrategy'](arg1);
}

export function SavePassword(arg1, arg2) {
  return window['go']['app']['App']['SavePassword'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['app']['App']['SelectFile']();
}

export function SelectFiles() {
  return window['go']['app']['App']['SelectFiles']();
}

export function SelectFilesForCompress() {
  return window['go']['app']['App']['SelectFilesForCompress']();
}

export function SelectFolderForCompress() {
  return window['go']['app']['App']['SelectFolderForCompress']();
}

export function SelectSavePath(arg1) {
  return window['go']['app']['App']['SelectSavePath'](arg1);
}

export function SetAppConfig(arg1, arg2) {
  return window['go']['app']['App']['SetAppConfig'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['app']['App']['SetTheme'](arg1);
}

export function TestArchive(arg1) {
  return window['go']['app']['App']['TestArchive'](arg1);
}

export function UpdatePasswordRecord(arg1, arg2) {
  return window['go']['app']['App']['UpdatePasswordRecord'](arg1, arg2);
}
