// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {history} from '../models';
import {password} from '../models';
import {archive} from '../models';

export function BatchExtract(arg1:Array<string>,arg2:string):Promise<Array<app.BatchExtractResult>>;

export function DeletePasswordRecord(arg1:number):Promise<void>;

export function Extract(arg1:string,arg2:string):Promise<void>;

export function ExtractWithPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExtractWithRetry(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ExtractWithStrategy(arg1:string,arg2:string):Promise<void>;

export function GetAppConfig(arg1:string):Promise<string>;

export function GetExtractStrategies():Promise<Array<app.ExtractStrategy>>;

export function GetExtractStrategy(arg1:string):Promise<app.ExtractStrategy>;

export function GetHistory(arg1:number):Promise<Array<history.ExtractHistory>>;

export function GetPasswordCandidates(arg1:string):Promise<Array<string>>;

export function GetPasswordRecords():Promise<Array<password.PasswordRecord>>;

export function GetPasswordStats():Promise<password.PasswordStats>;

export function GetTheme():Promise<string>;

export function OpenDirectory(arg1:string):Promise<void>;

export function PreviewArchive(arg1:string):Promise<Array<archive.ArchiveEntry>>;

export function SaveExtractStrategy(arg1:app.ExtractStrategy):Promise<void>;

export function SavePassword(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SetAppConfig(arg1:string,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function TestArchive(arg1:string):Promise<boolean>;

export function UpdatePasswordRecord(arg1:number,arg2:string):Promise<void>;
