// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventsOn(eventName: string, callback: (...data: any) => void): () => void {
  return window['runtime']['EventsOn'](eventName, callback);
}

export function EventsOff(eventName: string, ...additionalEventNames: string[]): void {
  return window['runtime']['EventsOff'](eventName, ...additionalEventNames);
}

export function EventsOnce(eventName: string, callback: (...data: any) => void): void {
  return window['runtime']['EventsOnce'](eventName, callback);
}

export function EventsEmit(eventName: string, ...data: any): void {
  return window['runtime']['EventsEmit'](eventName, ...data);
}

export function WindowReload(): void {
  return window['runtime']['WindowReload']();
}

export function WindowCenter(): void {
  return window['runtime']['WindowCenter']();
}

export function WindowSetTitle(title: string): void {
  return window['runtime']['WindowSetTitle'](title);
}

export function WindowFullscreen(): void {
  return window['runtime']['WindowFullscreen']();
}

export function WindowUnfullscreen(): void {
  return window['runtime']['WindowUnfullscreen']();
}

export function LogPrint(message: string): void {
  return window['runtime']['LogPrint'](message);
}

export function LogTrace(message: string): void {
  return window['runtime']['LogTrace'](message);
}

export function LogDebug(message: string): void {
  return window['runtime']['LogDebug'](message);
}

export function LogInfo(message: string): void {
  return window['runtime']['LogInfo'](message);
}

export function LogWarning(message: string): void {
  return window['runtime']['LogWarning'](message);
}

export function LogError(message: string): void {
  return window['runtime']['LogError'](message);
}

export function LogFatal(message: string): void {
  return window['runtime']['LogFatal'](message);
}
