// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Extract(arg1: string, arg2: string): Promise<void> {
  return window['go']['main']['App']['Extract'](arg1, arg2);
}

export function SelectDirectory(): Promise<string> {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(): Promise<string> {
  return window['go']['main']['App']['SelectFile']();
}
