// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

declare const window: any;

export function BatchExtract(arg1: string[], arg2: string): Promise<any[]> {
  return window['go']['main']['App']['BatchExtract'](arg1, arg2);
}

export function DeletePasswordRecord(arg1: number): Promise<void> {
  return window['go']['main']['App']['DeletePasswordRecord'](arg1);
}

export function Extract(arg1: string, arg2: string): Promise<void> {
  return window['go']['main']['App']['Extract'](arg1, arg2);
}

export function ExtractWithPassword(arg1: string, arg2: string, arg3: string): Promise<void> {
  return window['go']['main']['App']['ExtractWithPassword'](arg1, arg2, arg3);
}

export function GetHistory(arg1: number): Promise<any[]> {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetPasswordCandidates(arg1: string): Promise<string[]> {
  return window['go']['main']['App']['GetPasswordCandidates'](arg1);
}

export function GetPasswordRecords(): Promise<any[]> {
  return window['go']['main']['App']['GetPasswordRecords']();
}

export function GetPasswordStats(): Promise<any> {
  return window['go']['main']['App']['GetPasswordStats']();
}

export function OpenDirectory(arg1: string): Promise<void> {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function SavePassword(arg1: string, arg2: string): Promise<void> {
  return window['go']['main']['App']['SavePassword'](arg1, arg2);
}

export function SelectDirectory(): Promise<string> {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(): Promise<string> {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFiles(): Promise<string[]> {
  return window['go']['main']['App']['SelectFiles']();
}

export function TestArchive(arg1: string): Promise<boolean> {
  return window['go']['main']['App']['TestArchive'](arg1);
}

export function PreviewArchive(arg1: string): Promise<any[]> {
  return window['go']['main']['App']['PreviewArchive'](arg1);
}

export function GetTheme(): Promise<string> {
  return window['go']['main']['App']['GetTheme']();
}

export function SetTheme(arg1: string): Promise<void> {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function GetExtractStrategies(): Promise<any[]> {
  return window['go']['main']['App']['GetExtractStrategies']();
}

export function SaveExtractStrategy(arg1: any): Promise<void> {
  return window['go']['main']['App']['SaveExtractStrategy'](arg1);
}

export function ExtractWithStrategy(arg1: string, arg2: string): Promise<void> {
  return window['go']['main']['App']['ExtractWithStrategy'](arg1, arg2);
}
